- name: Deploy mongod_init config 
  template:
    src: "mongod/mongod_init.conf.j2"
    dest: "{{mongodb_config_dir}}/mongod.conf"
    mode: "0755"
    owner: mongod
    group: mongod

- name: Restart the mongod service when config changed
  systemd: 
    name: mongod
    state: restarted 
    daemon_reload: yes 
    enabled: yes

- name: wait when mongodb is started
  wait_for:
    host: "127.0.0.1"
    port: "{{ mongod_port }}"
    delay: 5
    timeout: 120

- name: create administrative user "{{mongodb_admin_user}}"
  mongodb_user:
    database: admin
    name: "{{mongodb_admin_user}}"
    password: "{{mongodb_admin_pass}}"
    update_password: "{{mongodb_update_password}}"
    roles: "userAdminAnyDatabase,root"
    login_host: "127.0.0.1"
    login_port: "{{mongod_port}}"

- name: Deploy mongod config 
  template:
    src: "mongod/mongod.conf.j2"
    dest: "{{mongodb_config_dir}}/mongod.conf"
    mode: "0755"
    owner: mongod
    group: mongod

- name: Restart the mongod service when config changed
  systemd: 
    name: mongod
    state: restarted 
    daemon_reload: yes 
    enabled: yes
 
