---
- hosts: all
  tasks:
    - systemd: 
        name: "{{item}}"
        state: stopped 
        daemon_reload: yes 
        enabled: no
      ignore_errors: yes
      with_items:
        - mongod

    - file: path=/var/run/mongodb state=absent
    - file: path=/var/log/mongodb state=absent
    - file: path=/var/lib/mongodb state=absent
    - file: path=/etc/systemd/system/mongod.service state=absent
    - file: path=/etc/mongodb state=absent